NAME = [[.Name]]
SRC  = src/boot.asm
BUILD_DIR = build
TARGET = $(BUILD_DIR)/$(NAME).bin

all: $(TARGET)

$(TARGET): $(SRC) | $(BUILD_DIR)
	nasm -f bin -o $(TARGET) $(SRC)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

run: $(TARGET)
	qemu-system-x86_64 -drive format=raw,file=$(TARGET)

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all run clean
