CC        = arm-none-eabi-gcc
CFLAGS    = -Wall -Wextra -mcpu=cortex-m4 -mthumb -nostdlib -O2
INCLUDES  = -Iinclude
SRC_DIR   = src
BUILD_DIR = build
NAME      = [[ .Name ]]

SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(SRCS:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)

all: $(BUILD_DIR)/$(NAME).elf

$(BUILD_DIR)/$(NAME).elf: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INCLUDES) -c -o $@ $<

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all clean
